let languages={
	'0':{
		"title":"Pdf Reader",
		"rotate":"Rotate",
		"vscroll":"Vertical Scrolling",
		"hscroll":"Horizontal Scrolling",
		"fpage":"Go to first page",
		"lpage":"Go to last page",
		"detail":"Details",
		"password_text":"Enter password to open this pdf file",
		"password":"Password",
		"cancel":"Cancel",
		"ok":"OK",
		"file_name":"File name:",
		"file_size":"File size:",
		"file_title":"Title:",
		"file_author":"Author:",
		"file_subject":"Subject:",
		"file_keyword":"Keywords:",
		"file_creation":"Creation Date:",
		"file_modification":"Modification Date:",
		"file_creator":"Creator:",
		"file_producer":"PDF Producer:",
		"file_version":"PDF Version:",
		"file_pagecount":"Page Count:",
		"file_pagesize":"Page Size:",
		"close":"Close",
		"file_information":"File Information",
		"search":{
			"title":"Search",
			"placeholder":"Search your pdf files here",
			"initial":"Search results will appear here",
			"noresults":"No pdf files found",
		},
	},
	'1':{//hindi
		"title":"पीडीएफ़ रीडर",
		"rotate":"घुमाएँ",
		"vscroll":"वर्टिकल स्क्रॉलिंग",
		"hscroll":"क्षैतिज स्क्रॉलिंग",
		"fpage":"पहले पृष्ठ पर जाएं",
		"lpage":"अंत पृष्ठ पर जाएं",
		"detail":"विवरण",
		"password_text":"इस पीडीएफ फाइल को खोलने के लिए पासवर्ड डालें",
		"password":"पासवर्ड",
		"cancel":"रद्द करना",
		"ok":"ठीक है",
		"file_name":"फ़ाइल का नाम:",
		"file_size":"फ़ाइल का साइज़:",
		"file_title":"शीर्षक:",
		"file_author":"लेखक:",
		"file_subject":"विषय:",
		"file_keyword":"कीवर्ड:",
		"file_creation":"निर्माण तिथि:",
		"file_modification":"सुधार की तारीख:",
		"file_creator":"बनाने वाला:",
		"file_producer":"पीडीएफ निर्माता:",
		"file_version":"पीडीएफ संस्करण:",
		"file_pagecount":"पृष्ठ संख्या:",
		"file_pagesize":"पृष्ठ आकार:",
		"close":"बंद करे",
		"file_information":"फ़ाइल जानकारी",
		"search":{
			"title":"खोज कर",
			"placeholder":"अपनी पीडीएफ फाइलों को यहां खोजें",
			"initial":"खोज परिणाम यहां दिखाई देंगे",
			"noresults":"कोई पीडीएफ फाइल नहीं मिली",
		},
	},
	'2':{//tamil
		"title":"பி.டி.எஃப் ரீடர்",
		"rotate":"சுழற்று",
		"vscroll":"செங்குத்து ஸ்க்ரோலிங்",
		"hscroll":"கிடைமட்ட ஸ்க்ரோலிங்",
		"fpage":"முதல் பக்கத்திற்குச் செல்லவும்",
		"lpage":"கடைசி பக்கத்திற்குச் செல்லவும்",
		"detail":"விவரங்கள்",
		"password_text":"இந்த பி.டி.எஃப் கோப்பைத் திறக்க கடவுச்சொல்லை உள்ளிடவும்",
		"password":"கடவுச்சொல்",
		"cancel":"ரத்துசெய்",
		"ok":"சரி",
		"file_name":"கோப்பு பெயர்:",
		"file_size":"கோப்பின் அளவு:",
		"file_title":"தலைப்பு:",
		"file_author":"நூலாசிரியர்:",
		"file_subject":"பொருள்:",
		"file_keyword":"முக்கிய வார்த்தைகள்:",
		"file_creation":"உருவாக்கும் தேதி:",
		"file_modification":"மாற்றியமைக்கும் தேதி:",
		"file_creator":"உருவாக்கியவர்:",
		"file_producer":"PDF தயாரிப்பாளர்:",
		"file_version":"PDF பதிப்பு:",
		"file_pagecount":"பக்க எண்ணிக்கை:",
		"file_pagesize":"பக்க அளவு:",
		"close":"நெருக்கமான",
		"file_information":"கோப்பு தகவல்",
		"search":{
			"title":"தேடல்",
			"placeholder":"உங்கள் பி.டி.எஃப் கோப்புகளை இங்கே தேடுங்கள்",
			"initial":"தேடல் முடிவுகள் இங்கே தோன்றும்",
			"noresults":"பி.டி.எஃப் கோப்புகள் எதுவும் கிடைக்கவில்லை",
		},
	},
	'3':{//malayalam
		"title":"പിഡിഎഫ് റീഡർ",
		"rotate":"തിരിക്കുക",
		"vscroll":"ലംബ സ്ക്രോളിംഗ്",
		"hscroll":"തിരശ്ചീന സ്ക്രോളിംഗ്",
		"fpage":"ആദ്യ പേജിലേക്ക് പോകുക",
		"lpage":"അവസാന പേജിലേക്ക് പോകുക",
		"detail":"വിശദാംശങ്ങൾ",
		"password_text":"ഈ പിഡിഎഫ് ഫയൽ തുറക്കാൻ പാസ്‌വേഡ് നൽകുക",
		"password":"Password",
		"cancel":"റദ്ദാക്കുക",
		"ok":"ശരി",
		"file_name":"ഫയലിന്റെ പേര്:",
		"file_size":"ഫയൽ വലുപ്പം:",
		"file_title":"ശീർഷകം:",
		"file_author":"രചയിതാവ്:",
		"file_subject":"വിഷയം:",
		"file_keyword":"കീവേഡുകൾ:",
		"file_creation":"സൃഷ്ടിക്കൽ തീയതി:",
		"file_modification":"പരിഷ്‌ക്കരിച്ച തീയതി:",
		"file_creator":"സ്രഷ്ടാവ്:",
		"file_producer":"PDF നിർമ്മാതാവ്:",
		"file_version":"PDF പതിപ്പ്:",
		"file_pagecount":"പേജ് എണ്ണം:",
		"file_pagesize":"പേജ് വലുപ്പം:",
		"close":"അടയ്‌ക്കുക",
		"file_information":"ഫയൽ വിവരങ്ങൾ",
		"search":{
			"title":"തിരയുക",
			"placeholder":"നിങ്ങളുടെ പിഡിഎഫ് ഫയലുകൾ ഇവിടെ തിരയുക",
			"initial":"തിരയൽ ഫലങ്ങൾ ഇവിടെ ദൃശ്യമാകും",
			"noresults":"പിഡിഎഫ് ഫയലുകളൊന്നും കണ്ടെത്തിയില്ല",
		},
	},
	'4':{//punjabi
		"title":"ਪੀਡੀਐਫ ਰੀਡਰ",
		"rotate":"ਘੁੰਮਾਓ",
		"vscroll":"ਲੰਬਕਾਰੀ ਸਕ੍ਰੌਲਿੰਗ",
		"hscroll":"ਹਰੀਜ਼ਟਲ ਸਕ੍ਰੌਲਿੰਗ",
		"fpage":"ਪਹਿਲੇ ਪੇਜ ਤੇ ਜਾਓ",
		"lpage":"ਆਖਰੀ ਪੇਜ ਤੇ ਜਾਓ",
		"detail":"ਵੇਰਵਾ",
		"password_text":"ਇਸ ਪੀਡੀਐਫ ਫਾਈਲ ਨੂੰ ਖੋਲ੍ਹਣ ਲਈ ਪਾਸਵਰਡ ਦਿਓ",
		"password":"ਪਾਸਵਰਡ",
		"cancel":"ਰੱਦ ਕਰੋ",
		"ok":"ਠੀਕ ਹੈ",
		"file_name":"ਫਾਈਲ ਦਾ ਨਾਮ:",
		"file_size":"ਫਾਈਲ ਅਕਾਰ:",
		"file_title":"ਸਿਰਲੇਖ:",
		"file_author":"ਲੇਖਕ:",
		"file_subject":"ਵਿਸ਼ਾ:",
		"file_keyword":"ਕੀਵਰਡਸ:",
		"file_creation":"ਬਣਾਉਣ ਦੀ ਮਿਤੀ:",
		"file_modification":"ਸੋਧ ਮਿਤੀ:",
		"file_creator":"ਸਿਰਜਣਹਾਰ:",
		"file_producer":"ਪੀਡੀਐਫ ਨਿਰਮਾਤਾ:",
		"file_version":"PDF ਵਰਜਨ:",
		"file_pagecount":"ਪੰਨਾ ਗਿਣਤੀ:",
		"file_pagesize":"ਪੇਜ ਦਾ ਆਕਾਰ:",
		"close":"ਬੰਦ ਕਰੋ",
		"file_information":"ਫਾਈਲ ਜਾਣਕਾਰੀ",
		"search":{
			"title":"ਖੋਜ",
			"placeholder":"ਆਪਣੀਆਂ ਪੀ ਡੀ ਐਫ ਫਾਈਲਾਂ ਇੱਥੇ ਲੱਭੋ",
			"initial":"ਖੋਜ ਨਤੀਜੇ ਇੱਥੇ ਪ੍ਰਗਟ ਹੋਣਗੇ",
			"noresults":"ਕੋਈ ਪੀਡੀਐਫ ਫਾਈਲਾਂ ਨਹੀਂ ਮਿਲੀਆਂ",
		},
	},
	'5':{//bangla
		"title":"পিডিএফ রিডার",
		"rotate":"ঘুরান",
		"vscroll":"উল্লম্ব স্ক্রোলিং",
		"hscroll":"অনুভূমিক স্ক্রোলিং",
		"fpage":"প্রথম পৃষ্ঠায় যান",
		"lpage":"শেষ পৃষ্ঠায় যান",
		"detail":"বিশদ",
		"password_text":"এই পিডিএফ ফাইলটি খুলতে পাসওয়ার্ড লিখুন",
		"password":"পাসওয়ার্ড",
		"cancel":"বাতিল",
		"ok":"ঠিক আছে",
		"file_name":"ফাইলের নাম:",
		"file_size":"ফাইলের আকার:",
		"file_title":"শিরোনাম:",
		"file_author":"লেখক:",
		"file_subject":"বিষয়:",
		"file_keyword":"কীওয়ার্ডস:",
		"file_creation":"তৈরির তারিখ:",
		"file_modification":"পরিবর্তন তারিখ:",
		"file_creator":"স্রষ্টা:",
		"file_producer":"পিডিএফ প্রযোজক:",
		"file_version":"পিডিএফ সংস্করণ:",
		"file_pagecount":"পৃষ্ঠা গোনা:",
		"file_pagesize":"পাতার আকার:",
		"close":"বন্ধ",
		"file_information":"ফাইল তথ্য",
		"search":{
			"title":"অনুসন্ধান করুন",
			"placeholder":"আপনার পিডিএফ ফাইলগুলি এখানে অনুসন্ধান করুন",
			"initial":"অনুসন্ধান ফলাফল এখানে প্রদর্শিত হবে",
			"noresults":"কোনও পিডিএফ ফাইল পাওয়া যায় নি",
		},
	},
	'6':{//gujarati
		"title":"પીડીએફ રીડર",
		"rotate":"ફેરવો",
		"vscroll":"વર્ટિકલ સ્ક્રોલિંગ",
		"hscroll":"આડા સ્ક્રોલિંગ",
		"fpage":"પ્રથમ પૃષ્ઠ પર જાઓ",
		"lpage":"અંતિમ પૃષ્ઠ પર જાઓ",
		"detail":"વિગતો",
		"password_text":"આ પીડીએફ ફાઇલ ખોલવા માટે પાસવર્ડ દાખલ કરો",
		"password":"પાસવર્ડ",
		"cancel":"રદ કરો",
		"ok":"બરાબર",
		"file_name":"ફાઈલનું નામ:",
		"file_size":"ફાઇલનું કદ:",
		"file_title":"શીર્ષક:",
		"file_author":"લેખક:",
		"file_subject":"વિષય:",
		"file_keyword":"કીવર્ડ્સ:",
		"file_creation":"બનાવટ તારીખ:",
		"file_modification":"ફેરફાર તારીખ:",
		"file_creator":"નિર્માતા:",
		"file_producer":"પીડીએફ નિર્માતા:",
		"file_version":"પીડીએફ સંસ્કરણ:",
		"file_pagecount":"પૃષ્ઠ ગણતરી:",
		"file_pagesize":"પૃષ્ઠનું કદ:",
		"close":"સજ્જડ",
		"file_information":"ફાઇલ માહિતી",
		"search":{
			"title":"શોધો",
			"placeholder":"તમારી પીડીએફ ફાઇલો અહીં શોધો",
			"initial":"શોધ પરિણામો અહીં દેખાશે",
			"noresults":"કોઈ પીડીએફ ફાઇલો મળી નથી",
		},
	},
	'7':{//spanish
		"title":"Lector PDF",
		"rotate":"Girar",
		"vscroll":"Desplazamiento vertical",
		"hscroll":"Desplazamiento horizontal",
		"fpage":"Ir a la primera pagina",
		"lpage":"Ir a la página final",
		"detail":"Detalles",
		"password_text":"Ingrese la contraseña para abrir este archivo pdf",
		"password":"Contraseña",
		"cancel":"Cancelar",
		"ok":"OK",
		"file_name":"Nombre del archivo:",
		"file_size":"Tamaño del archivo:",
		"file_title":"Título:",
		"file_author":"Autora:",
		"file_subject":"Sujeta:",
		"file_keyword":"Palabras clave:",
		"file_creation":"Fecha de creación:",
		"file_modification":"Fecha de modificación:",
		"file_creator":"Creadora:",
		"file_producer":"Productora PDF:",
		"file_version":"Versión PDF:",
		"file_pagecount":"Recuento de páginas:",
		"file_pagesize":"Tamaño de página:",
		"close":"Cerrar",
		"file_information":"Informacion del archivo",
		"search":{
			"title":"Buscar",
			"placeholder":"Busque sus archivos pdf aquí",
			"initial":"Los resultados de la búsqueda aparecerán aquí",
			"noresults":"No se encontraron archivos pdf",
		},
	},
	'8':{//chinese
		"title":"PDF阅读器",
		"rotate":"旋转",
		"vscroll":"垂直滚动",
		"hscroll":"水平滚动",
		"fpage":"转到第一页",
		"lpage":"转到结束页",
		"detail":"细节",
		"password_text":"输入密码以打开此pdf文件",
		"password":"密码",
		"cancel":"取消",
		"ok":"好的",
		"file_name":"文档名称:",
		"file_size":"文件大小:",
		"file_title":"标题:",
		"file_author":"作者:",
		"file_subject":"学科:",
		"file_keyword":"关键词:",
		"file_creation":"创建日期:",
		"file_modification":"修改日期:",
		"file_creator":"创作者:",
		"file_producer":"PDF制作人:",
		"file_version":"PDF版本:",
		"file_pagecount":"页数:",
		"file_pagesize":"页面大小:",
		"close":"关闭",
		"file_information":"文件信息",
		"search":{
			"title":"搜索",
			"placeholder":"在此處搜索您的pdf文件",
			"initial":"搜索結果將顯示在這裡",
			"noresults":"找不到pdf檔案",
		},
	},
	'9':{//Russian
		"title":"Читатель PDF",
		"rotate":"Повернуть",
		"vscroll":"Вертикальная прокрутка",
		"hscroll":"Горизонтальная прокрутка",
		"fpage":"На первую страницу",
		"lpage":"Перейти на конечную страницу",
		"detail":"Подробности",
		"password_text":"Введите пароль, чтобы открыть этот PDF-файл",
		"password":"Пароль",
		"cancel":"Отмена",
		"ok":"Ok",
		"file_name":"Имя файла:",
		"file_size":"Размер файла:",
		"file_title":"Заголовок:",
		"file_author":"Автор:",
		"file_subject":"Предмет:",
		"file_keyword":"Ключевые слова:",
		"file_creation":"Дата создания:",
		"file_modification":"Дата модификации:",
		"file_creator":"Создатель:",
		"file_producer":"Производитель PDF:",
		"file_version":"PDF версия:",
		"file_pagecount":"Количество страниц:",
		"file_pagesize":"Размер страницы:",
		"close":"Закрывать",
		"file_information":"Информация о файле",
		"search":{
			"title":"Поиск",
			"placeholder":"Найдите здесь свои файлы pdf",
			"initial":"Результаты поиска появятся здесь",
			"noresults":"PDF-файлов не найдено",
		},
	},
	'10':{//portuguese
		"title":"Leitor de PDF",
		"rotate":"Girar",
		"vscroll":"Rolagem Vertical",
		"hscroll":"Rolagem Horizontal",
		"fpage":"Vá para a primeira página",
		"lpage":"Vá para a página final",
		"detail":"Detalhes",
		"password_text":"Digite a senha para abrir este arquivo pdf",
		"password":"Senha",
		"cancel":"Cancel",
		"ok":"OK",
		"file_name":"Nome do arquivo:",
		"file_size":"Tamanho do arquivo:",
		"file_title":"Título:",
		"file_author":"Autora:",
		"file_subject":"Sujeita:",
		"file_keyword":"Palavras-chave:",
		"file_creation":"Data de criação:",
		"file_modification":"Modificação de data:",
		"file_creator":"Criadora:",
		"file_producer":"Produtor de PDF:",
		"file_version":"Versão PDF:",
		"file_pagecount":"Contagem de páginas:",
		"file_pagesize":"Tamanho da páginae:",
		"close":"Fechar",
		"file_information":"Informação do arquivo",
		"search":{
			"title":"Procurar",
			"placeholder":"Pesquise seus arquivos PDF aqui",
			"initial":"Os resultados da pesquisa irão aparecer aqui",
			"noresults":"Nenhum arquivo pdf encontrado",
		},
	},
	'11':{//japanese
		"title":"PDFリーダー",
		"rotate":"回転する",
		"vscroll":"垂直スクロール",
		"hscroll":"水平スクロール",
		"fpage":"最初のページに移動",
		"lpage":"終了ページに移動",
		"detail":"細部",
		"password_text":"このPDFファイルを開くにはパスワードを入力してください",
		"password":"パスワード",
		"cancel":"キャンセル",
		"ok":"OK",
		"file_name":"ファイル名:",
		"file_size":"ファイルサイズ:",
		"file_title":"Title:",
		"file_author":"著者:",
		"file_subject":"件名:",
		"file_keyword":"キーワード:",
		"file_creation":"作成日:",
		"file_modification":"変更日:",
		"file_creator":"クリエイター:",
		"file_producer":"PDFプロデューサー:",
		"file_version":"PDF版:",
		"file_pagecount":"ページ数:",
		"file_pagesize":"ページサイズ:",
		"close":"閉じる",
		"file_information":"ファイル情報",
		"search":{
			"title":"探す",
			"placeholder":"ここでPDFファイルを検索します",
			"initial":"検索結果はここに表示されます",
			"noresults":"PDFファイルが見つかりません",
		},
	},
	'12':{//korean
		"title":"PDF 리더",
		"rotate":"회전",
		"vscroll":"수직 스크롤",
		"hscroll":"수평 스크롤",
		"fpage":"첫 페이지로 이동",
		"lpage":"끝 페이지로 이동",
		"detail":"세부",
		"password_text":"이 PDF 파일을 열려면 비밀번호를 입력하세요.",
		"password":"암호",
		"cancel":"취소",
		"ok":"확인",
		"file_name":"파일 이름:",
		"file_size":"파일 크기:",
		"file_title":"표제:",
		"file_author":"저자:",
		"file_subject":"제목:",
		"file_keyword":"키워드:",
		"file_creation":"생산 일:",
		"file_modification":"수정일:",
		"file_creator":"창조자:",
		"file_producer":"PDF 생산자:",
		"file_version":"PDF 버전:",
		"file_pagecount":"페이지 수:",
		"file_pagesize":"페이지 크기:",
		"close":"닫기",
		"file_information":"파일 정보",
		"search":{
			"title":"검색",
			"placeholder":"여기에서 PDF 파일 검색",
			"initial":"여기에 검색 결과가 표시됩니다.",
			"noresults":"pdf 파일이 없습니다.",
		},
	},
	'13':{
		//french
		"title":"Lecteur PDF",
		"rotate":"Tourner",
		"vscroll":"Défilement vertical",
		"hscroll":"Défilement horizontal",
		"fpage":"Aller à la première page",
		"lpage":"Aller à la page de fin",
		"detail":"Des détails",
		"password_text":"Entrez le mot de passe pour ouvrir ce fichier pdf",
		"password":"Mot de passe",
		"cancel":"Annuler",
		"ok":"d'accord",
		"file_name":"Nom de fichier:",
		"file_size":"Taille du fichier:",
		"file_title":"Titre:",
		"file_author":"Auteure:",
		"file_subject":"Sujette:",
		"file_keyword":"Mots clés:",
		"file_creation":"Date de création:",
		"file_modification":"Date de modification:",
		"file_creator":"Créatrice:",
		"file_producer":"Producteur PDF:",
		"file_version":"Version PDF:",
		"file_pagecount":"Nombre de pages:",
		"file_pagesize":"Taille de la page:",
		"close":"Fermer",
		"file_information":"Informations sur le fichier",
		"search":{
			"title":"Rechercher",
			"placeholder":"Recherchez vos fichiers pdf ici",
			"initial":"Les résultats de la recherche apparaîtront ici",
			"noresults":"Aucun fichier pdf trouvé",
		},
	},
	'14':{//german
        "title":"Pdf Reader",
		"rotate":"Drehen",
		"vscroll":"Vertikales Scrollen",
		"hscroll":"Horizontales Scrollen",
		"fpage":"Zur ersten Seite gehen",
		"lpage":"Zur Endseite gehen",
		"detail":"Einzelheiten",
		"password_text":"Geben Sie das Passwort ein, um diese PDF-Datei zu öffnen",
		"password":"Passwort",
		"cancel":"Stornieren",
		"ok":"OK",
		"file_name":"Dateinamen:",
		"file_size":"Dateigröße:",
		"file_title":"Titel:",
		"file_author":"Autorin:",
		"file_subject":"Gegenstand:",
		"file_keyword":"Schlüsselwörter:",
		"file_creation":"Erstellungsdatum:",
		"file_modification":"Änderungsdatum:",
		"file_creator":"Schöpferin:",
		"file_producer":"PDF-Produzent:",
		"file_version":"PDF-Version:",
		"file_pagecount":"Seitenzahl:",
		"file_pagesize":"Seitengröße:",
		"close":"schließen",
		"file_information":"Dateiinformationen",
		"search":{
			"title":"Suche",
			"placeholder":"Suchen Sie hier Ihre PDF-Dateien",
			"initial":"Suchergebnisse werden hier angezeigt",
			"noresults":"Keine PDF-Dateien gefunden",
		},
    },
	'15':{
		//italian
		"title":"Pdf Reader",
		"rotate":"Ruotare",
		"vscroll":"Scorrimento verticale",
		"hscroll":"Scorrimento orizzontale",
		"fpage":"Vai alla prima pagina",
		"lpage":"Vai alla pagina finale",
		"detail":"Details",
		"password_text":"Immettere la password per aprire questo file pdf",
		"password":"Parola d'ordine",
		"cancel":"Annulla",
		"ok":"OK",
		"file_name":"Nome del file:",
		"file_size":"Dimensione del file:",
		"file_title":"Titolo:",
		"file_author":"Autrice:",
		"file_subject":"Soggetta:",
		"file_keyword":"Parole chiave:",
		"file_creation":"Data di creazione:",
		"file_modification":"Data di modifica:",
		"file_creator":"Creatrice:",
		"file_producer":"Produttore PDF:",
		"file_version":"Versione PDF:",
		"file_pagecount":"Conteggio pagine:",
		"file_pagesize":"Dimensioni della pagina:",
		"close":"Vicina",
		"file_information":"Informazioni sul file",
		"search":{
			"title":"Ricerca",
			"placeholder":"Cerca qui i tuoi file pdf",
			"initial":"I risultati della ricerca verranno visualizzati qui",
			"noresults":"Nessun file pdf trovato",
		},
	},
}
export default languages;